### ISSUE TITLE
Could you please provide the packaged .jar?

### ISSUE THREAD

**Issue by mhoangvslev** [jimjonesbr/wmss#1]
I could not build it manually with ```mvn package```.

**Comment by jimjonesbr** [comment]
Hey there! Thanks for your message.
In Eclipse I am able to generate a single jar file using maven with the goal `assembly:single`. Can you test it?

**Comment by mhoangvslev** [comment]
> Hey there! Thanks for your message.
> In Eclipse I am able to generate a single jar file using maven with the goal `assembly:single`. Can you test it?

It works!
```mvn assembly:single```

**Comment by jimjonesbr** [comment]
Awesome. Happy coding :)
